--和熠光显 16 张表原始结构

--这张表的数据来自“D:\code\python\pandas_demo\efd\日报涉及表结构与数据样例.xlsx” 这个文件的“ODS_MES_MM_MATERIAL”这个sheet的第193到203行
--其中193行是表头，每一列和这个表的每一列一一对应
CREATE TABLE "RPTDW"."ODS_MES_MM_MATERIAL"
	( "OBJECT_RRN" NUMBER(19,0) NOT NULL ENABLE,
	"ORG_RRN" NUMBER(19,0),
	"IS_ACTIVE" VARCHAR2(1),
	"CREATED" DATE,
	"CREATED_BY" VARCHAR2(32),
	"UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(32),
	"LOCK_VERSION" NUMBER(19,0),
	"NAME" VARCHAR2(32),
	"DESCRIPTION" VARCHAR2(256),
	"VERSION" NUMBER(19,0),
	"STATUS" VARCHAR2(32),
	"ACTIVE_TIME" DATE,
	"ACTIVE_USER" VARCHAR2(32),
	"CLASS" VARCHAR2(32),
	"IS_GLOBAL" VARCHAR2(1),
	"PROCESS_NAME" VARCHAR2(32),
	"PROCESS_VERSION" NUMBER(19,0),
	"PARTNER_CODE" NUMBER(19,0),
	"EAN" VARCHAR2(32),
	"SKU" VARCHAR2(32),
	"UOM_ID" VARCHAR2(32),
	"CATEGORY" VARCHAR2(32),
	"MATERIAL_TYPE" VARCHAR2(100),
	"SUB_MATERIAL_TYPE" VARCHAR2(32),
	"GROUP1" VARCHAR2(32),
	"GROUP2" VARCHAR2(32),
	"GROUP3" VARCHAR2(32),
	"GROUP4" VARCHAR2(32),
	"CLASSIFICATION" VARCHAR2(32),
	"SPEC1" VARCHAR2(32),
	"SPEC2" VARCHAR2(32),
	"SPEC3" VARCHAR2(32),
	"SPEC4" VARCHAR2(32),
	"BOM_VERIFIED" VARCHAR2(32),
	"IS_PRODUCTION" VARCHAR2(1),
	"IS_PHANTOM" VARCHAR2(1),
	"STATUS_MODEL_RRN" NUMBER(19,0),
	"SAFETY_STOCK_QTY" NUMBER,
	"MAX_STOCK_QTY" NUMBER,
	"NUMBER_OF_PACK" NUMBER(19,0),
	"NUMBER_OF_PALLET" NUMBER(19,0),
	"BATCH_TYPE" VARCHAR2(1),
	"LOT_SIZE" NUMBER,
	"SUB_LOT_SIZE" NUMBER,
	"ID_GENERATOR" VARCHAR2(32),
	"IS_TIME_SENSITIVE" VARCHAR2(1),
	"SHELF_WARNING" NUMBER(19,0),
	"SHELF_LIFE" NUMBER(19,0),
	"SHELF_LIFE_UNIT" VARCHAR2(32),
	"FLOOR_LIFE" NUMBER(19,0),
	"FLOOR_LIFE_UNIT" VARCHAR2(32),
	"FLOOR_LIFE_ACTIVATOR" VARCHAR2(32),
	"LIMIT_WARNING" NUMBER(19,0),
	"LIMIT_LIFE" NUMBER(19,0),
	"VOLUME" NUMBER,
	"WEIGHT" NUMBER,
	"SHELF_WIDTH" NUMBER,
	"SHELF_HEIGHT" NUMBER,
	"SHELF_DEPTH" NUMBER,
	"OWNER1" VARCHAR2(32),
	"OWNER2" VARCHAR2(32),
	"COMMENTS" VARCHAR2(4000),
	"RESERVED1" VARCHAR2(256),
	"RESERVED2" VARCHAR2(256),
	"RESERVED3" VARCHAR2(256),
	"RESERVED4" VARCHAR2(256),
	"RESERVED5" VARCHAR2(256),
	"RESERVED6" VARCHAR2(256),
	"RESERVED7" VARCHAR2(256),
	"RESERVED8" VARCHAR2(256),
	"WAREHOUSE_RRN" NUMBER(19,0),
	"MAIN_MAT_TYPE" VARCHAR2(256),
	"SUB_MAT_TYPE" VARCHAR2(256),
	"STYLE" NUMBER,
	"DISPLAY_VERSION" VARCHAR2(32),
	"PACKAGE_HIERARCHY_NAME" VARCHAR2(32),
	"TENANT_ID" VARCHAR2(32),
	"INIT_GRADE" VARCHAR2(32),
	"REWORK_LIMIT_COUNT" NUMBER(19,0),
	"LIMIT_CLEAN_COUNT" NUMBER(19,0),
	"IS_NEED_CLEAN" VARCHAR2(1),
	"LIMIT_USE_COUNT" NUMBER(19,0),
	"FLOOR_LIFE_RESET" VARCHAR2(1),
	"UPDATE_TIME" DATE
	) SEGMENT CREATION IMMEDIATE
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
	NOCOMPRESS LOGGING
	TABLESPACE "ODS_MES_HIS_12M_DAT" ;
	CREATE UNIQUE INDEX "RPTDW"."ODS_MES_MM_MATERIAL_PK" ON "RPTDW"."ODS_MES_MM_MATERIAL" ("OBJECT_RRN")
	PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING
	TABLESPACE "ODS_MES_HIS_12M_IDX" ;
	CREATE UNIQUE INDEX "RPTDW"."ODS_MES_MM_MATERIAL_U" ON "RPTDW"."ODS_MES_MM_MATERIAL" ("ORG_RRN", "NAME", "VERSION")
	PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING
	TABLESPACE "ODS_MES_HIS_12M_IDX" ;
	ALTER TABLE "RPTDW"."ODS_MES_MM_MATERIAL" ADD CONSTRAINT "PK_MM_MATERIAL" PRIMARY KEY ("OBJECT_RRN")
	USING INDEX "RPTDW"."ODS_MES_MM_MATERIAL_PK" ENABLE;
	ALTER TABLE "RPTDW"."ODS_MES_MM_MATERIAL" ADD CONSTRAINT "UK_MM_MATERIAL" UNIQUE ("ORG_RRN", "NAME", "VERSION")
	USING INDEX "RPTDW"."ODS_MES_MM_MATERIAL_U" ENABLE;

	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.OBJECT_RRN IS '对象序列号';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.ORG_RRN IS '区域ID';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_ACTIVE IS '对象是否生效';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.CREATED IS '创建时间';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.CREATED_BY IS '创建人ID';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.UPDATED IS '更新时间';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.UPDATED_BY IS '更新人ID';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LOCK_VERSION IS '锁定版本';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.NAME IS '物料名称';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.DESCRIPTION IS '描述';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.VERSION IS '物料版本';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.STATUS IS '状态';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.ACTIVE_TIME IS '激活时间';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.ACTIVE_USER IS '激活用户名';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.CLASS IS '类型 (成品\半成品\原料)';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_GLOBAL IS '是否全局';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.PROCESS_NAME IS '工艺名称';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.PROCESS_VERSION IS '工艺版本';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.PARTNER_CODE IS '供应商代码';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.EAN IS 'EAN码<商品用条码>';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SKU IS '保存库存控制的最小可用单位 (每种产品均对应有唯一的SKU号)';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.UOM_ID IS '物料单位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.CATEGORY IS '类别';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.MATERIAL_TYPE IS '物料类型';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SUB_MATERIAL_TYPE IS '子物料类型';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.GROUP1 IS '物料组别1';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.GROUP2 IS '物料组别2';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.GROUP3 IS '物料组别3';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.GROUP4 IS '物料组别4';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.CLASSIFICATION IS '物料ABC分类法';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SPEC1 IS '物料规格1';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SPEC2 IS '物料规格2';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SPEC3 IS '物料规格3';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SPEC4 IS '物料规格4';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.BOM_VERIFIED IS '物料清单验证';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_PRODUCTION IS '是否生产物料';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_PHANTOM IS '是否虚拟料';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.STATUS_MODEL_RRN IS '状态模型主键';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SAFETY_STOCK_QTY IS '安全库存量';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.MAX_STOCK_QTY IS '最大库存量';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.NUMBER_OF_PACK IS '包装数量';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.NUMBER_OF_PALLET IS '托盘数量';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.BATCH_TYPE IS 'Batch类型';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LOT_SIZE IS '批次大小';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SUB_LOT_SIZE IS '子批次大小';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.ID_GENERATOR IS '批号规则';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_TIME_SENSITIVE IS '是否时间敏感物料';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_WARNING IS '保质警告期';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_LIFE IS '保质期';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_LIFE_UNIT IS '保质期单位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.FLOOR_LIFE IS '使用有效期';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.FLOOR_LIFE_UNIT IS '使用有效期单位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.FLOOR_LIFE_ACTIVATOR IS '何时使用(生产接受时使用/设备绑定时使用/手动使用等)';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LIMIT_WARNING IS '次数警告期';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LIMIT_LIFE IS '次数有效期';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.VOLUME IS '体积';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.WEIGHT IS '重量';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_WIDTH IS '宽度';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_HEIGHT IS '高度';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SHELF_DEPTH IS '深度';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.OWNER1 IS '责任组1';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.OWNER2 IS '责任组2';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.COMMENTS IS '备注';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED1 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED2 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED3 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED4 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED5 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED6 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED7 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.RESERVED8 IS '预留栏位';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.WAREHOUSE_RRN IS '仓库主键';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.MAIN_MAT_TYPE IS '主物料类型';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.SUB_MAT_TYPE IS '子物料类型';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL."STYLE" IS 'STYLE';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.DISPLAY_VERSION IS '显示版本';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.PACKAGE_HIERARCHY_NAME IS '包装层级';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.TENANT_ID IS '租户(多租户预留)';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.INIT_GRADE IS '产品初始化等级';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.REWORK_LIMIT_COUNT IS '可返工次数';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LIMIT_CLEAN_COUNT IS '清洗数限制';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.IS_NEED_CLEAN IS '是否需要清洗';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.LIMIT_USE_COUNT IS '限制使用次数(变Dirty)';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.FLOOR_LIFE_RESET IS '有效期是否重置(Y/N';
	COMMENT ON COLUMN RPTDW.ODS_MES_MM_MATERIAL.UPDATE_TIME IS '数据更新时间';


